### PR TITLE
switching out for the new url

### LINKED ISSUE #252: Can we make 'your extracts' URL friendlier?
Instead of https://mapzen.com/data/metro-extracts/odes/extracts/
can it be https://mapzen.com/data/metro-extracts/your-extracts/

### PR DESCRIPTION
**Pull request by binx**
closes #252 

* [x] set up new route
* [x] set up redirect from /odes/extracts/
* [x] update tests

### CODE REVIEW

**Comment by migurski** [comment]
You're writing Python!

**Comment by binx** [comment]
I'm string-replacing in Python ;)

**Comment by migurski** [comment]
Still though. I will pick up some of the redirect stuff here.

**Comment by migurski** [comment]
Instead of redirects, I just made sure that the old links continue to work. New people will get the new ones.

**Pull request merged**
