### PR TITLE
making your extracts always visible

### LINKED ISSUE #257: 'your custom extracts' should always be visible
Currently, it only appears when user is signed in, which might not always be the case even if user has signed up before. Changing those links on the user can be confusing.

Let's have it always visible and if user is not signed up/signed in we can link to the [GitHub auth page](https://mapzen.com/developers/sign_in?return_to=%2Foauth%2Fauthorize%3Fclient_id%3Da2a33afb941f7b915672d73e2b1dd61c35960a4c2005d57a3273402478066831%26response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fmapzen.com%252Fdata%252Fmetro-extracts%252Foauth%252Fcallback%26state%3D19d86181-c00d-4262-99cf-918ad6d0c181) ( < THIS IS THE LONGEST LINK I HAVE EVER SEEN)

### PR DESCRIPTION
**Pull request by binx**
closes #257

### CODE REVIEW

**Comment by binx** [comment]
@souperneon fwiw, the reason @migurski was assigned this was because I wanted to confirm with him that hitting "my extracts" without being logged in would trigger a login, and I get to test it on heroku yet.

**Comment by souperneon** [comment]
Whoops! sorry @binx @migurski can we back track?

**Comment by migurski** [comment]
Back track?

**Comment by binx** [comment]
@migurski don't worry about it, we're all good

**Comment by souperneon** [comment]
@migurski is it rollback? i don't know, like time machine to before I merged the PR ;)

**Pull request merged**
